name: Backend Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run BE Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run cy:run:api
